theme: jekyll-theme-cayman
gems: ['jekyll-github-metadata']
title: Triangle Aquaponics
description: TriangleAquaponics.com is a website dedicated to supporting the hydroponic, aquaponic, indoor agriculture and worm farmers in the Triangle region of NC. All ad revenue, donations, or other monetary gifts go directly to supporting projects or costs associated with the maintenance of the website. Triangle Aquaponics is a community and not a registered non-profit organization. Donations to projects or support functions are not tax-deductible.
show_downloads: true
google_analytics:

# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      comments: false
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      comments: false
